# Generated by Django 4.1.2 on 2022-10-27 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('similar_movies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmbeddingModel',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
